import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const currentDir = dirname(fileURLToPath(import.meta.url));
const appSource = readFileSync(resolve(currentDir, '../App.tsx'), 'utf8');
const uiSource = readFileSync(resolve(currentDir, '../components/UI/UI.tsx'), 'utf8');
const mapSceneSource = readFileSync(resolve(currentDir, '../components/AudioVisualizer/MapScene.tsx'), 'utf8');
const spatialLyricsSource = readFileSync(resolve(currentDir, '../components/AudioVisualizer/SpatialLyrics3D.tsx'), 'utf8');

assert.match(appSource, /const \[currentLyricsText, setCurrentLyricsText\] = useState\(''\)/);
assert.match(appSource, /const \[lyricsVisible, setLyricsVisible\] = useState\(true\)/);
assert.match(appSource, /onCurrentLyricsChange=\{setCurrentLyricsText\}/);
assert.match(appSource, /onLyricsVisibilityChange=\{setLyricsVisible\}/);
assert.match(appSource, /lyricsText=\{currentLyricsText \|\| null\}/);
assert.match(appSource, /lyricsVisible=\{lyricsVisible\}/);
assert.doesNotMatch(appSource, /lyricsText=\{currentSong\?\.lyrics/);

assert.match(uiSource, /onCurrentLyricsChange\?: \(lyrics: string\) => void/);
assert.match(uiSource, /onLyricsVisibilityChange\?: \(visible: boolean\) => void/);
assert.match(uiSource, /onCurrentLyricsChange\?\.\(lyricsText\)/);
assert.match(uiSource, /onLyricsVisibilityChange\?\.\(displaySettings\.showLyrics\)/);

const platterGroupIndex = mapSceneSource.indexOf('<group ref={visualPlatterRef}>');
const platterGroupEndIndex = mapSceneSource.indexOf('\n      </group>', platterGroupIndex);
const spatialLyricsIndex = mapSceneSource.indexOf('<SpatialLyrics3D');
const coverIndex = mapSceneSource.indexOf('<coverShaderMaterial');
assert.ok(platterGroupIndex >= 0 && platterGroupEndIndex > platterGroupIndex, 'MapScene should render a visual platter group');
assert.ok(spatialLyricsIndex > platterGroupEndIndex, '3D lyrics should stay outside the rotating platter');
assert.ok(coverIndex > platterGroupEndIndex, 'cover screen should stay outside the rotating platter');
assert.match(mapSceneSource, /lyricsSettings\?\.style === 'spatial-wall' && lyricsText/);
assert.match(mapSceneSource, /lyricsVisible = true/);
assert.match(mapSceneSource, /lyricsVisible\?: boolean/);
assert.match(mapSceneSource, /visible=\{lyricsVisible\}/);

assert.match(spatialLyricsSource, /parseLRC\(lrcText\)/);
assert.match(spatialLyricsSource, /splitLineToMeasuredWidth/);
assert.match(spatialLyricsSource, /wrapLyricTextLines\(activeLine\.text, lyricsSettings\.maxCharsPerLine\)/);
assert.match(spatialLyricsSource, /export const COVER_SCREEN_POSITION = \[110, 24, -110\] as const/);
assert.match(spatialLyricsSource, /export const COVER_SCREEN_ROTATION = \[0, -Math\.PI \/ 4, 0\] as const/);
assert.match(spatialLyricsSource, /export const SPATIAL_LYRICS_LEFT_OFFSET = 18/);
assert.match(spatialLyricsSource, /COVER_SCREEN_POSITION\[0\] - Math\.cos\(Math\.PI \/ 4\) \* SPATIAL_LYRICS_LEFT_OFFSET/);
assert.match(spatialLyricsSource, /COVER_SCREEN_POSITION\[2\] - Math\.sin\(Math\.PI \/ 4\) \* SPATIAL_LYRICS_LEFT_OFFSET/);
assert.match(spatialLyricsSource, /const DEFAULT_SPATIAL_LYRICS_RADIUS = Math\.hypot\(SPATIAL_LYRICS_POSITION\[0\], SPATIAL_LYRICS_POSITION\[2\]\)/);
assert.match(spatialLyricsSource, /const DEFAULT_SPATIAL_LYRICS_ANGLE = Math\.atan2\(SPATIAL_LYRICS_POSITION\[2\], SPATIAL_LYRICS_POSITION\[0\]\)/);
assert.match(spatialLyricsSource, /const spatialOrbitOffsetRadians = THREE\.MathUtils\.degToRad\(lyricsSettings\.spatialOrbitOffset\)/);
assert.match(spatialLyricsSource, /const spatialLyricsPosition = useMemo\(\(\) =>/);
assert.match(spatialLyricsSource, /Math\.cos\(angle\) \* DEFAULT_SPATIAL_LYRICS_RADIUS/);
assert.match(spatialLyricsSource, /Math\.sin\(angle\) \* DEFAULT_SPATIAL_LYRICS_RADIUS/);
assert.match(spatialLyricsSource, /const SPATIAL_LYRICS_ARC_HALF_ANGLE = 0\.58/);
assert.match(spatialLyricsSource, /const SPATIAL_LYRICS_THETA_START = Math\.PI \+ SPATIAL_LYRICS_ARC_HALF_ANGLE/);
assert.match(spatialLyricsSource, /const SPATIAL_LYRICS_THETA_LENGTH = -SPATIAL_LYRICS_ARC_HALF_ANGLE \* 2/);
assert.doesNotMatch(spatialLyricsSource, /texture\.repeat\.x = -1/);
assert.match(spatialLyricsSource, /new THREE\.CanvasTexture\(canvasInactive\)/);
assert.match(spatialLyricsSource, /new THREE\.CanvasTexture\(canvasActive\)/);
assert.match(spatialLyricsSource, /const visualEnergyRef = useRef\(0\)/);
assert.doesNotMatch(spatialLyricsSource, /setVisualEnergy/);
assert.match(spatialLyricsSource, /const baseHex = lyricsSettings\.fontColor/);
assert.match(spatialLyricsSource, /const currentAudioTime = engine\.audioElement\.currentTime/);
assert.match(spatialLyricsSource, /const \[activeIndex, setActiveIndex\] = useState\(-1\)/);
assert.match(spatialLyricsSource, /let newIndex = -1/);
assert.doesNotMatch(spatialLyricsSource, /calculateKaraokeProgress/);
assert.doesNotMatch(spatialLyricsSource, /mixHexColor/);
assert.doesNotMatch(spatialLyricsSource, /SPATIAL_LYRICS_TEXTURE_FPS/);
assert.doesNotMatch(spatialLyricsSource, /for \(let offset = -4; offset <= 4; offset\+\+\)/);
assert.match(spatialLyricsSource, /const activeLine = lyricsData\[activeIndex\]/);
assert.match(spatialLyricsSource, /function renderCurrentLyricTextures\(\)/);
assert.match(spatialLyricsSource, /visible = true/);
assert.match(spatialLyricsSource, /visible\?: boolean/);
assert.match(spatialLyricsSource, /const opacityRef = useRef\(0\)/);
assert.match(spatialLyricsSource, /if \(visible && !meshRef\.current\.visible\) \{/);
assert.match(spatialLyricsSource, /meshRef\.current\.visible = true/);
assert.match(spatialLyricsSource, /if \(!visible && opacityRef\.current <= 0\.01\) \{/);
assert.match(spatialLyricsSource, /meshRef\.current\.visible = false/);
assert.doesNotMatch(spatialLyricsSource, /ctx\.createLinearGradient/);
assert.doesNotMatch(spatialLyricsSource, /const ACTIVE_TEXT_MAX_WIDTH = 1320/);
assert.match(spatialLyricsSource, /const CANVAS_SAFE_TEXT_WIDTH = 1880/);
assert.match(spatialLyricsSource, /const estimateTargetLineWidth = \(maxCharsPerLine: number, fontSize: number\) =>/);
assert.match(spatialLyricsSource, /const targetLineWidth = estimateTargetLineWidth\(lyricsSettings\.maxCharsPerLine, fontSize\)/);
assert.match(spatialLyricsSource, /const ACTIVE_MAX_FONT_SIZE = 260/);
assert.match(spatialLyricsSource, /const SPATIAL_LYRICS_MAX_LINES = 8/);
assert.match(spatialLyricsSource, /const LINE_BOUNDS_HALF_STEP_RATIO = 0\.48/);
assert.doesNotMatch(spatialLyricsSource, /const DEFAULT_ACTIVE_FONT_SIZE = 236/);
assert.doesNotMatch(spatialLyricsSource, /const ACTIVE_MIN_FONT_SIZE = 190/);
assert.match(spatialLyricsSource, /THREE\.MathUtils\.clamp\(scaledSettingFontSize, ACTIVE_MIN_FONT_SIZE, ACTIVE_MAX_FONT_SIZE\)/);
assert.match(spatialLyricsSource, /fitWrappedLinesToCanvasWidth\(wrappedLines, ctxInactive, targetLineWidth\)/);
assert.doesNotMatch(spatialLyricsSource, /Array\.from\(line\)/);
assert.match(spatialLyricsSource, /const lineStep = Math\.min\(fontSize \* 1\.36, 1720 \/ Math\.max\(1, wrappedLines\.length\)\)/);
assert.match(spatialLyricsSource, /const lineBoundsHalfHeight = Math\.min\(fontSize \* 0\.66, lineStep \* LINE_BOUNDS_HALF_STEP_RATIO\)/);
assert.match(spatialLyricsSource, /const topY = y - lineBoundsHalfHeight/);
assert.match(spatialLyricsSource, /const bottomY = y \+ lineBoundsHalfHeight/);
assert.doesNotMatch(spatialLyricsSource, /const topY = y - fontSize \* 0\.7/);
assert.doesNotMatch(spatialLyricsSource, /const bottomY = y \+ fontSize \* 0\.7/);
assert.match(spatialLyricsSource, /textures\.inactive\.needsUpdate = true/);
assert.match(spatialLyricsSource, /textures\.active\.needsUpdate = true/);
const useFrameIndex = spatialLyricsSource.indexOf('useFrame((state, delta) => {');
const useFrameEndIndex = spatialLyricsSource.indexOf('\n  });', useFrameIndex);
const useFrameSource = spatialLyricsSource.slice(useFrameIndex, useFrameEndIndex);
assert.doesNotMatch(useFrameSource, /renderCurrentLyricTexture/);
assert.doesNotMatch(useFrameSource, /texture\.needsUpdate/);
assert.match(spatialLyricsSource, /fog=\{false\}/);
assert.match(spatialLyricsSource, /depthTest=\{false\}/);
assert.match(spatialLyricsSource, /toneMapped=\{false\}/);
assert.match(spatialLyricsSource, /depthWrite=\{false\}/);
assert.doesNotMatch(spatialLyricsSource, /finalColor\.rgb \*= uBaseColor/);
assert.match(spatialLyricsSource, /uBaseColor\.value\.setRGB\(1\.0, 1\.0, 1\.0\)/);
assert.match(spatialLyricsSource, /const SPATIAL_LYRICS_FONT_SCALE = 4/);
assert.match(spatialLyricsSource, /const SPATIAL_LYRICS_WORLD_SCALE = 5/);
assert.match(spatialLyricsSource, /const scaledSettingFontSize = lyricsSettings\.activeFontSize \* SPATIAL_LYRICS_FONT_SCALE/);
assert.match(spatialLyricsSource, /const targetScale = SPATIAL_LYRICS_WORLD_SCALE \* \(1\.0 \+ reactiveEnergy \* 0\.28\)/);
assert.match(spatialLyricsSource, /meshRef\.current\.scale\.set\(pulseRef\.current, pulseRef\.current, pulseRef\.current\)/);
assert.match(spatialLyricsSource, /const targetY = spatialLyricsPosition\[1\] \+ Math\.sin\(state\.clock\.elapsedTime \* 0\.5\) \* 1\.5/);
assert.match(spatialLyricsSource, /const spatialLyricsWidthScale = useMemo\(\(\) =>/);
assert.match(spatialLyricsSource, /const spatialLyricsRadius = 52 \* spatialLyricsWidthScale/);
assert.match(spatialLyricsSource, /cylinderGeometry args=\{\[spatialLyricsRadius, spatialLyricsRadius, 46, 64, 1, true, SPATIAL_LYRICS_THETA_START, SPATIAL_LYRICS_THETA_LENGTH\]\}/);
assert.match(spatialLyricsSource, /<mesh ref=\{meshRef\} position=\{spatialLyricsPosition\} rotation=\{spatialLyricsRotation\}>/);
assert.doesNotMatch(spatialLyricsSource, /<mesh ref=\{meshRef\} position=\{SPATIAL_LYRICS_POSITION\} rotation=\{COVER_SCREEN_ROTATION\}>/);
assert.match(mapSceneSource, /mesh position=\{COVER_SCREEN_POSITION\} rotation=\{COVER_SCREEN_ROTATION\}/);
assert.match(uiSource, /maxCharsPerLine: DEFAULT_MAX_CHARS_PER_LINE/);
assert.match(uiSource, /spatialOrbitOffset: DEFAULT_SPATIAL_ORBIT_OFFSET/);
assert.match(uiSource, /左右环绕位置|宸﹀彸鐜粫浣嶇疆/);
assert.match(uiSource, /min=\{SPATIAL_ORBIT_OFFSET_MIN\}/);
assert.match(uiSource, /max=\{SPATIAL_ORBIT_OFFSET_MAX\}/);
assert.match(uiSource, /updateConfig\(\{ spatialOrbitOffset: Number\(e\.target\.value\) \}\)/);
assert.match(uiSource, /每行歌词容量/);
assert.match(uiSource, /max=\{MAX_CHARS_PER_LINE_MAX\}/);
assert.match(uiSource, /updateConfig\(\{ maxCharsPerLine: Number\(e\.target\.value\) \}\)/);

console.log('spatial lyrics scene tests passed');
